"""test_version

Revision ID: b86354bace64
Revises: 
Create Date: 2023-08-24 15:44:00.327623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b86354bace64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('build_test_noter',
    # sa.Column('version', sa.String(length=80), nullable=False),
    # sa.Column('releaseplan', sa.String(length=80), nullable=True),
    # sa.Column('testprocess', sa.String(length=80), nullable=True),
    # sa.Column('testcycle', sa.String(length=80), nullable=True),
    # sa.Column('issues', sa.String(length=80), nullable=False),
    # sa.Column('meeting', sa.String(length=120), nullable=False),
    # sa.PrimaryKeyConstraint('version')
    # )
    op.drop_table('testcases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcases',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('steps', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('build_test_noter')
    # ### end Alembic commands ###
